### PR TITLE
"databaseComment" setting

### PR DESCRIPTION
**Pull request by gramian**
## What does this PR do?

This adds a `arcadedb.databaseComment` setting which allows to add metadata about the database.

## Motivation

Providing context about a database.

## Additional Notes

This is a (very much) simpler version of the `DESCRIBE DATABASE` command PR https://github.com/ArcadeData/arcadedb/pull/1485

## Checklist

- [X] I have run the build using `mvn clean package` command
- [ ] My unit tests cover both failure and success scenarios

### CODE REVIEW

**Comment by gramian** [comment]
@lvca WDYT?

**Comment by lvca** [comment]
If you have 2 databases open, which database has the comment?

**Comment by gramian** [comment]
Oh, I thought `SCOPE.DATABASE` means each database gets its own instance?

**Comment by gramian** [comment]
I see. This voids this PR.

**Pull request closed without merging**
