### PR TITLE
Refactor isEmbeddedX in ResultInternal

### PR DESCRIPTION
**Pull request by gramian**
## What does this PR do?

This change refactors `isEmbeddedSet`, `isEmbeddedMap`, `isEmbeddedList` in `ResultInternal` to allow early exit and avoid multiple casts.

## Motivation

Benchmarking `isEmbeddedMap` turned out to be the dominant consumer of CPU time, and while the recursive cost cannot be reduced, this refactoring can help reducing overhead.

## Checklist

- [X] I have run the build using `mvn clean package` command
- [ ] My unit tests cover both failure and success scenarios

### CODE REVIEW

**Comment by lvca** [comment]
Hey @gramian I don't see any advantage in terms of performance here. What's the cost that has been reduced?

**Comment by gramian** [comment]
This an attempt to slightly simplify the code structure.
Old version: https://godbolt.org/z/nnfsPcWbM
Proposed: https://godbolt.org/z/hzeqqPesx

**Comment by lvca** [comment]
@gramian Moving the cast shouldn't get any improvements in speed, but I could be wrong. Try with a test case that executes that method millions of times.

If that method is a hot spot, we could look into it. I see it's checking recursively to find a Record object, but I believe that could be simplified. I see that methods are called from `ResultInternal.wrap`, but I don't see why we need to wrap the content in that way. It could be something we inherited from OrientDB that doesn't apply anymore.

Out of curiosity, if you comment out the calling of those methods in `ResultInternal.wrap`, do you see a gain in performance?

**Comment by lvca** [comment]
Ok, I've changed the implementation, realizing the method didn't work correctly. It should be also faster.

**Comment by gramian** [comment]
@lvca Do you still want me to test with commenting out a call to the recursive methods in `wrap`?

**Comment by lvca** [comment]
Reopening this PR only for discussion. I believe originally the OrientDB's `ResultInternal.wrap()` was designed to avoid returning records. This was a risk with OrientDB because records were mutable. With ArcadeDB, all the records returned from a query are immutable, so I'd like to explore the removal of the explicit call to `.wrap()` in `ResultInternal.getProperty()`.

**Comment by lvca** [comment]
Ok, moving this conversation to https://github.com/ArcadeData/arcadedb/issues/1576.

**Pull request closed without merging**
