### PR TITLE
Feature 253/cleanup logging

### PR DESCRIPTION
**Pull request by arcade-player**
What does this PR do?

implements logging cleanup as per #253

### CODE REVIEW

**Comment by lvca** [comment]
There is a reason behind having multiple methods with an increasing number of arguments. In Java, if you have `Object ... args`, The JVM creates an array, copy values in it and pass it to the method. Instead, having methods that receive a 1 to N number of arguments in the signature prevent such overhead.

**Comment by lvca** [comment]
Logging methods should have a weight closest to zero, especially if they are not logging because of the configured level. Having `Object...` means creating 1 array object + copy every time even if the logging is not logging.

**Comment by arcade-player** [comment]
You're right, but:
- even in the case of multiple args, in the end there's a call to `String.format` inside the `DefaultLogger` that  uses varargs
- there aren't so many calls with multiple arfs AND
- arcadedb logs only when it's necessary, logging speed/overhead is not an issue, IMHO
- this pr removes also all the calls with the exception parameter set to null

IMHO, no impact on performances at all, lower complexity, less code to be maintained

**Comment by lvca** [comment]
Hard to tell what has been removed and added back with the log interface. Merging and testing on main branch for a while.

**Pull request merged**
