### PR TITLE
TLS improvements

### PR DESCRIPTION
**Pull request by lucian-cm**
- Fixed defect with Undertow's TLS truststore and TLS keystore sharing the same password
- Undertow's TLS default keystore type is read from `javax.net.ssl.keyStoreType` if valid, otherwise it is `PKCS12` (previously it was hardcoded to JKS)
- Undertow's TLS default truststore type is read from `javax.net.ssl.trustStoreType` system property if valid, otherwise it is `JKS` (previously it was hardcoded to JKS)
- Using latest TLS protocol `TLSv1.3` for Undertow's HTTPS listener (previously it was not guaranteed to be TLSv1.3)
- Refactored some of the TLS handling logic

### CODE REVIEW

**Comment by lucian-cm** [comment]
@lvca, this is in relation to https://github.com/ArcadeData/arcadedb/issues/775 
Please take a look when you can.

**Comment by lvca** [comment]
Hi @lucian-cm, thanks, for checking it asap. Did you install pre-commit? https://github.com/ArcadeData/arcadedb/blob/main/CONTRIBUTING.md#pre-commit

**Comment by lucian-cm** [comment]
> Hi @lucian-cm, thanks, for checking it asap. Did you install pre-commit? https://github.com/ArcadeData/arcadedb/blob/main/CONTRIBUTING.md#pre-commit



> Hi @lucian-cm, thanks, for checking it asap. Did you install pre-commit? https://github.com/ArcadeData/arcadedb/blob/main/CONTRIBUTING.md#pre-commit

Thanks for your reply. I forgot to add the pre-commit checker before. I added it now and did not find anything to fix. It appears that the following tests are failing, which I believe are not related to my changes. 

Results:
2023-02-12T21:50:59.8062567Z [INFO] 
2023-02-12T21:50:59.8069175Z [ERROR] Failures: 
2023-02-12T21:50:59.8077961Z [ERROR]   DateTest.testInstant:392 expected: <2023-02-12T21:21:20.963787Z> but was: <2023-02-12T21:21:20.963787900Z>
2023-02-12T21:50:59.8078476Z [ERROR]   DateTest.testSQLMath:449 expected: <true> but was: <false>
2023-02-12T21:50:59.8079213Z [ERROR]   DateTest.testZonedDateTime:343 expected: <true> but was: <false>
2023-02-12T21:50:59.8079570Z [ERROR] Errors: 
2023-02-12T21:50:59.8125883Z [ERROR]   UpdateStatementExecutionTest.testLocalDateTimeUpsertWithIndex:892->lambda$testLocalDateTimeUpsertWithIndex$1:894 � DuplicatedKey Duplicated key [2023-02-12T21:48:59.484061, 2023-02-12T21:48:59.484061] found on index 'Product_1_25
80549119200' already assigned to record #9:0

Second test I saw the problem is the fact that the saved value for date 1 is less than the original date1, such that that the test has a wrong expected value to include the left margin date1
date1 = 2023-02-13T10:33:26.869755500
date2 = 2023-02-13T10:33:27.869755500
result contains just the right side which is normal given the dates=2023-02-13T10:33:27.869755

a fix would be 
image

**Comment by lvca** [comment]
Thanks @lucian-cm, merged!

**Pull request merged**
