### PR TITLE
Make ArcadeDB stable

### PR DESCRIPTION
**Pull request by tglman**

### CODE REVIEW

**Comment by arcade-player** [comment]
please install pre-commit to let the build pass:
 
https://github.com/ArcadeData/arcadedb/blob/main/CONTRIBUTING.md#pre-commit

**Comment by lvca** [comment]
I appreciate your irony here @tglman :-) Perhaps you should spend this time working on OrientDB instead. I'd start with a synchronous journal that doesn't lose transactions in case of a crash. Or by completely replacing the old, slow, and buggy plocal engine with something fast and more secure, like RocksDB? Just a couple of suggestions ;-)

But if you change your mind and you want to be part of ArcadeDB, you are always welcome!

**Comment by laa** [comment]
@lvca Probably would be better to add MVRBTree instead? The fastest index ever?

**Comment by laa** [comment]
Or maybe would be better to copy one of implementation of one of the absolutely non-working implementations of distributed storage because all of them had zero bugs in the bug tracker? Just a couple of suggestions.

**Comment by lvca** [comment]
@laa Surprised you're monitoring the ArcadeDB project :-) I don't want to waste too much time here talking about why OrientDB is in such bad shape today... But this is the beauty of Open Source: @laa and @tglman, please show everybody that I'm totally wrong, that the current OrientDB engine is not a monster and make OrientDB better, faster and safer ;-)

**Comment by tglman** [comment]
Hi, 
I actually pointed @laa  to this PR, it was just fun, I must reject the offer of help, I'm not used to work on such high quality code

**Pull request closed without merging**
