### PR TITLE
#412 multiplatfrom image

### PR DESCRIPTION
**Pull request by arcade-player**
## What does this PR do?
- move to zulu-openjdk ad base image
- move to kubernetes-maven-plugin to build the Docker image

## Motivation
provde docker image that support more CPUs/OS

## Related issues
#412 
#408

### CODE REVIEW

**Comment by MrHassanMurtaza** [comment]
@arcade-player any update on when this PR will get accepted? We plan to run the ArcadeDB on arm64 especially Mac M1 for the local kubernetes cluster.

**Comment by arcade-player** [comment]
@MrHassanMurtaza could you please test this branch on your side and confirm that the image created is good for M1?

It would be very valuable for us.

If you have `gh` installed, just do:
```
gh pr checkout 456
mvn clean install -Pdocker  -DskipTests
```

then 
```
docker run --rm  -p 2480:2480 -p 2424:2424 -p 6379:6379 -p 5432:5432 \
           --env arcadedb.server.rootPassword=playwithdata \
           --env arcadedb.server.defaultDatabases="Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" \
           --env arcadedb.server.plugins="Redis:com.arcadedb.redis.RedisProtocolPlugin, MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin, Postgres:com.arcadedb.postgres.PostgresProtocolPlugin" \
            arcadedata/arcadedb:latest
```

We are still facing problem activating the Gremlin plugin

**Comment by vaidotasstankus** [comment]
@arcade-player it builds successfully:

> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for ArcadeDB 22.6.2-SNAPSHOT:
> [INFO]
> [INFO] ArcadeDB ........................................... SUCCESS [  0.351 s]
> [INFO] arcadedb-engine .................................... SUCCESS [  4.783 s]
> [INFO] arcadedb-network ................................... SUCCESS [  0.126 s]
> [INFO] arcadedb-integration ............................... SUCCESS [  0.252 s]
> [INFO] arcadedb-server .................................... SUCCESS [  2.828 s]
> [INFO] arcadedb-console ................................... SUCCESS [  0.123 s]
> [INFO] arcadedb-gremlin ................................... SUCCESS [  3.968 s]
> [INFO] arcadedb-graphql ................................... SUCCESS [  0.279 s]
> [INFO] arcadedb-mongodbw .................................. SUCCESS [  0.334 s]
> [INFO] arcadedb-redisw .................................... SUCCESS [  0.111 s]
> [INFO] arcadedb-postgresw ................................. SUCCESS [  1.294 s]
> [INFO] arcadedb-coverage .................................. SUCCESS [  0.008 s]
> [INFO] arcadedb-package ................................... SUCCESS [ 16.991 s]
> [INFO] arcadedb-e2e ....................................... SUCCESS [  0.156 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  31.681 s
> [INFO] Finished at: 2022-08-10T18:18:09+03:00
> [INFO] ------------------------------------------------------------------------

but hangs during startup:

> ❯ docker run --rm  -p 2480:2480 -p 2424:2424 -p 6379:6379 -p 5432:5432 \
>            --env arcadedb.server.rootPassword=playwithdata \
>            --env arcadedb.server.defaultDatabases="Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" \
>            --env arcadedb.server.plugins="Redis:com.arcadedb.redis.RedisProtocolPlugin, MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin, Postgres:com.arcadedb.postgres.PostgresProtocolPlugin" \
>             arcadedata/arcadedb:latest
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> 
>  █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
> ██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
> ███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
> ██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
> ██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
> ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
> PLAY WITH DATA                                    arcadedb.com
> Can't load log handler "java.util.logging.FileHandler"
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
> 	at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:512)
> 	at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:279)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.base/java.lang.Class.newInstance(Class.java:584)
> 	at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
> 	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
> 	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
> 	at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
> 	at com.arcadedb.log.DefaultLogger.installCustomFormatter(DefaultLogger.java:79)
> 	at com.arcadedb.log.DefaultLogger.<init>(DefaultLogger.java:41)
> 	at com.arcadedb.log.DefaultLogger.<clinit>(DefaultLogger.java:36)
> 	at com.arcadedb.log.LogManager.<init>(LogManager.java:31)
> 	at com.arcadedb.log.LogManager.<clinit>(LogManager.java:29)
> 	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:98)
> 	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:90)
> Can't load log handler "java.util.logging.FileHandler"
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
> 	at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:512)
> 	at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:279)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.base/java.lang.Class.newInstance(Class.java:584)
> 	at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
> 	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
> 	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
> 	at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
> 	at com.arcadedb.log.DefaultLogger.installCustomFormatter(DefaultLogger.java:79)
> 	at com.arcadedb.log.DefaultLogger.<init>(DefaultLogger.java:41)
> 	at com.arcadedb.log.LogManager.<init>(LogManager.java:31)
> 	at com.arcadedb.log.LogManager.<clinit>(LogManager.java:29)
> 	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:98)
> 	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:90)
> 
> 2022-08-10 15:19:47.513 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v22.6.2-SNAPSHOT (build a3572a4d0a677dfb988e741514351a40914ef0db/1660144658987/feature-412/multiplatform_docker_image) is starting up...
> 2022-08-10 15:19:47.521 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [Redis,  MongoDB,  Postgres] ...
> 2022-08-10 15:19:47.615 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
> 2022-08-10 15:19:47.896 INFO  [ServerSecurity] <ArcadeDB_0> Creating root user with the provided password
> 2022-08-10 15:19:48.778 INFO  [ArcadeDBServer] <ArcadeDB_0> Creating default database 'Imported'...
> 2022-08-10 15:19:49.503 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz...

waited for ~15h before killing it. Can be that I run into CPU issue:
> CONTAINER ID   NAME               CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O     PIDS
> 54b2ab8a3185   dazzling_khorana   101.05%   357.5MiB / 9.703GiB   3.60%     13.3kB / 3.05kB   0B / 1.88MB   30

later will try with more CPU allocated.

**Comment by lvca** [comment]
To me seems there is something wrong with the setup of the directory. The `log` folder is missing?

**Comment by vaidotasstankus** [comment]
I had increased CPUs to 8 (from 4), had made a restart of Docker Desktop and had managed to pass the step where was getting stuck. CPU utilization is still ~100%, but maybe that is normal. Currently am waiting on `Creation of edges started: creating edges between vertices`. If I manage to pass this step, then will try to reduce amount of CPUs back to 4, restart DD and try once again. DD is prone to get into problematic states. Want to be sure that it was not DD causing trouble.

Regarding logs. I still receive those exceptions. Logs folder within container seems to be present (it is empty):
image

**Comment by vaidotasstankus** [comment]
It didn't go past the point I had waiting on while writing the last comment. Had to delete that container to stop it. The last lines I saw:

> Creation of records started: creating vertices and documents records (edges on the next phase)
>  - Creation of records completed: created 7,467 vertices and 0 documents, skipped 14,908 edges (1,866 records/sec elapsed=4 secs)
>  - Status update: parsed 7,484 (1,871/sec) - 0 documents (0/sec) - 7,467 vertices (1,866/sec) - 0 edges (0/sec) - 14,908 skipped edges - 0 linked edges (0/sec - 0%)
> Creation of edges started: creating edges between vertices

**Without changing anything** decided to try one more run and had managed to get to the point where studio had started 🤷:

> docker run --rm  -p 2480:2480 -p 2424:2424 -p 6379:6379 -p 5432:5432 \
>            --env arcadedb.server.rootPassword=playwithdata \
>            --env arcadedb.server.defaultDatabases="Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}" \
>            --env arcadedb.server.plugins="Redis:com.arcadedb.redis.RedisProtocolPlugin, MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin, Postgres:com.arcadedb.postgres.PostgresProtocolPlugin" \
>             arcadedata/arcadedb:latest
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> 
>  █████╗ ██████╗  ██████╗ █████╗ ██████╗ ███████╗██████╗ ██████╗
> ██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗
> ███████║██████╔╝██║     ███████║██║  ██║█████╗  ██║  ██║██████╔╝
> ██╔══██║██╔══██╗██║     ██╔══██║██║  ██║██╔══╝  ██║  ██║██╔══██╗
> ██║  ██║██║  ██║╚██████╗██║  ██║██████╔╝███████╗██████╔╝██████╔╝
> ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═════╝
> PLAY WITH DATA                                    arcadedb.com
> Can't load log handler "java.util.logging.FileHandler"
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
> 	at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:512)
> 	at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:279)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.base/java.lang.Class.newInstance(Class.java:584)
> 	at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
> 	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
> 	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
> 	at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
> 	at com.arcadedb.log.DefaultLogger.installCustomFormatter(DefaultLogger.java:79)
> 	at com.arcadedb.log.DefaultLogger.<init>(DefaultLogger.java:41)
> 	at com.arcadedb.log.DefaultLogger.<clinit>(DefaultLogger.java:36)
> 	at com.arcadedb.log.LogManager.<init>(LogManager.java:31)
> 	at com.arcadedb.log.LogManager.<clinit>(LogManager.java:29)
> 	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:98)
> 	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:90)
> Can't load log handler "java.util.logging.FileHandler"
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> java.nio.file.NoSuchFileException: log/arcadedb.log.0.lck
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
> 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
> 	at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:512)
> 	at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:279)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.base/java.lang.Class.newInstance(Class.java:584)
> 	at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
> 	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
> 	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
> 	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
> 	at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
> 	at com.arcadedb.log.DefaultLogger.installCustomFormatter(DefaultLogger.java:79)
> 	at com.arcadedb.log.DefaultLogger.<init>(DefaultLogger.java:41)
> 	at com.arcadedb.log.LogManager.<init>(LogManager.java:31)
> 	at com.arcadedb.log.LogManager.<clinit>(LogManager.java:29)
> 	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:98)
> 	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:90)
> 
> 2022-08-12 15:26:26.672 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v22.6.2-SNAPSHOT (build a3572a4d0a677dfb988e741514351a40914ef0db/1660144658987/feature-412/multiplatform_docker_image) is starting up...
> 2022-08-12 15:26:26.677 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [Redis,  MongoDB,  Postgres] ...
> 2022-08-12 15:26:26.761 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
> 2022-08-12 15:26:27.010 INFO  [ServerSecurity] <ArcadeDB_0> Creating root user with the provided password
> 2022-08-12 15:26:27.864 INFO  [ArcadeDBServer] <ArcadeDB_0> Creating default database 'Imported'...
> 2022-08-12 15:26:28.584 INFO  [SourceDiscovery] <ArcadeDB_0> Analyzing url: https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz...
> 2022-08-12 15:26:32.474 INFO  [SourceDiscovery] <ArcadeDB_0> Recognized format OrientDB (parsingLimitBytes=9.54MB parsingLimitEntries=0)
> 2022-08-12 15:26:32.476 INFO  [Importer] <ArcadeDB_0> Checking schema...Importing OrientDB database from stream to '../databases/Imported'
> Creation of the schema: types, properties and indexes
> - Status update: parsed 0 (0/sec) - 0 documents (0/sec) - 0 vertices (0/sec) - 0 edges (0/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
> - Created type 'V' with the following properties {}
> - Created type 'Beer' with the following properties {id=INTEGER}
> - Created type 'Brewery' with the following properties {id=INTEGER}
> - Created type 'Category' with the following properties {id=INTEGER}
> - Created type 'E' with the following properties {}
> - Created type 'HasBrewery' with the following properties {}
> - Created type 'HasCategory' with the following properties {}
> - Created type 'HasStyle' with the following properties {}
> - Created type 'Style' with the following properties {id=INTEGER}
> - Created index UNIQUE on Beer[id]
> - Created index UNIQUE on Brewery[id]
> - Created index UNIQUE on Style[id]
> - Created index UNIQUE on Category[id]
> Creation of records started: creating vertices and documents records (edges on the next phase)
> - Creation of records completed: created 7,467 vertices and 0 documents, skipped 14,908 edges (1,866 records/sec elapsed=4 secs)
> Creation of edges started: creating edges between vertices
> - Status update: parsed 7,484 (1,496/sec) - 0 documents (0/sec) - 7,467 vertices (1,493/sec) - 0 edges (0/sec) - 14,908 skipped edges - 0 linked edges (0/sec - 0%)
> - Creation of edges completed: created 14,908 edges {HasStyle=4433, HasBrewery=5901, HasCategory=4574} (1,656 edges/sec elapsed=9 secs)
> Dropping empty 'V' base vertex type (in OrientDB all the vertices have their own class
> Dropping empty 'E' base edge type (in OrientDB all the edges have their own class
> ***************************************************************************************************
> Import of OrientDB database completed in 9 secs with 0 errors and 0 warnings.
> 
> SUMMARY
> 
> - Records..................................: 7,484
> -- Beer                                    : 5,901
> -- Brewery                                 : 1,414
> -- Category                                : 11
> -- E                                       : 0
> -- HasBrewery                              : 5,901
> -- HasCategory                             : 4,574
> -- HasStyle                                : 4,433
> -- OFunction                               : 0  (excluded)
> -- OIdentity                               : 0  (excluded)
> -- ORestricted                             : 0  (excluded)
> -- ORole                                   : 3  (excluded)
> -- OSchedule                               : 0  (excluded)
> -- OSecurityPolicy                         : 4  (excluded)
> -- OSequence                               : 0  (excluded)
> -- OTriggered                              : 0  (excluded)
> -- OUser                                   : 3  (excluded)
> -- Style                                   : 141
> -- V                                       : 0
> -- _studio                                 : 7  (excluded)
> - Total attributes.........................: 513,424
> ***************************************************************************************************
> 
> NOTES:
> - users stored in OUser class will not be imported because ArcadeDB has users only at server level. If you want to import such users into ArcadeDB server configuration, please run the importer with the option -s <securityFileDirectory>
> - you can find your new ArcadeDB database in '../databases/Imported'
> - Status update: parsed 0 (-1,871/sec) - 0 documents (0/sec) - 7,467 vertices (0/sec) - 14,908 edges (3,727/sec) - 0 skipped edges - 0 linked edges (0/sec - 0%)
> 
> 2022-08-12 15:26:42.832 INFO  [RedisNetworkListener] <ArcadeDB_0> Listening for incoming connections on 0.0.0.0:6379 (protocol v.-1)
> 2022-08-12 15:26:42.837 INFO  [ArcadeDBServer] <ArcadeDB_0> - Redis plugin started[main] INFO de.bwaldvogel.mongo.MongoServer - started MongoServer(port: 27017, ssl: false)
> 
> 2022-08-12 15:26:43.541 INFO  [ArcadeDBServer] <ArcadeDB_0> -  MongoDB plugin started
> 2022-08-12 15:26:43.561 INFO  [PostgresNetworkListener] <ArcadeDB_0> Listening for incoming connections on 0.0.0.0:5432 (protocol v.-1)
> 2022-08-12 15:26:43.563 INFO  [ArcadeDBServer] <ArcadeDB_0> -  Postgres plugin started
> 2022-08-12 15:26:43.564 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489)...
> 2022-08-12 15:26:43.747 INFO  [undertow] starting server: Undertow - 2.2.18.Final
> 2022-08-12 15:26:43.783 INFO  [xnio] XNIO version 3.8.7.Final
> 2022-08-12 15:26:43.826 INFO  [nio] XNIO NIO Implementation Version 3.8.7.Final
> 2022-08-12 15:26:43.936 INFO  [threads] JBoss Threads version 3.1.0.Final
> 2022-08-12 15:26:44.100 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480)
> 2022-08-12 15:26:44.103 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [mongo, gremlin, cypher, graphql, sql]
> 2022-08-12 15:26:44.104 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started (CPUs=8 MAXRAM=2.00GB)
> 2022-08-12 15:26:44.104 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://localhost:2480

Not sure what does this necessity to run several times to get through mean. Say if you need some additional info. Now, when studio is running, CPU usage is below 1%.

**Comment by arcade-player** [comment]
Another update on this PR. I moved to temurin as base image, but `--env` stopped to work. So, to pass properties, the new way is:

```
docker run --rm  -p 2480:2480 -p 2424:2424 -p 6379:6379 -p 5432:5432 -p 8182:8182 \
           --env JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata \
                      -Darcadedb.server.defaultDatabases=OpenBeer[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz} \
                      -Darcadedb.server.plugins=Redis:com.arcadedb.redis.RedisProtocolPlugin,MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin,Postgres:com.arcadedb.postgres.PostgresProtocolPlugin,GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin "  \
         arcadedata/arcadedb:latest
```

The startup time, on my machine, is really fast.

**Review by lvca — APPROVED** [review]

**Pull request merged**
